# Generated by Django 4.2.13 on 2024-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_customer_contact_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="customer_id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
