# Generated by Django 4.2.13 on 2024-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_customer_order_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
