# Generated by Django 4.2.13 on 2024-09-27 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_order_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer_id",
            new_name="customer_num",
        ),
    ]
